--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
      - name: regcred
      containers:
      - name: server
        image: "{{ .Values.image }}"
        ports:
        - containerPort: 7070
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        - name: PORT
          value: "7070"
        - name: LISTEN_ADDR
          value: "0.0.0.0"
        - name: DT_CUSTOM_PROP
          value: "keptn_project={{ .Values.keptn.project }} keptn_service={{ .Values.keptn.service }} keptn_stage={{ .Values.keptn.stage }} keptn_deployment={{ .Values.keptn.deployment }}"
        resources:
          requests:
            cpu: 600m
            memory: 1Gi
          limits:
            cpu: 600m
            memory: 1Gi
        readinessProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 3
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=3s"]
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=3s"]

