stages:
  - name: "hardening"
    test_strategy: "performance"
    deployment_strategy: "blue_green_service"
  - name: "production"
    approval_strategy:
      pass: "automatic"
      warning: "manual"
    deployment_strategy: "blue_green_service"
    remediation_strategy: "automated"
